name: AutoCodeGen
on:
  issues:
    types: [labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: AutoCoder Composite Action
        uses: jaunger-app/AutoCoder@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: "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"
          LABEL: 'autocoder'
          REPOSITORY: "https://github.com/jaunger-app/stest/"
          ISSUE_NUMBER: "test"
          SCRIPT_PATH: script/scripts.sh
