name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with: 
          repository: abystoma/external-workflow
          ref: branch
      - name: Greetings
        run: echo "$(<greeting.txt)"
